version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nivek_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: unless-stopped
 
  core-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.core-api
    container_name: nivek_core_api
    depends_on:
      - postgres
    environment:
      - APP_NAME=${APP_NAME}
      - CORE_API_PORT=${CORE_API_PORT}
      - CORE_API_LISTEN_ADDRESS=${CORE_API_LISTEN_ADDRESS}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
    networks:
      - app-network
    ports:
      - "8080:8080"
    restart: unless-stopped

  nivek-vue:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VUE_APP_API_URL=http://localhost
    depends_on:
      - core-api

volumes:
  postgres_data:
    name: postgres_data

networks:
  app-network:
    driver: bridge
